name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Seed production environment config
        run: |
          cp src/environments/environment.prod.example.tsx src/environments/environment.prod.tsx
          sed -i 's#https://example-api-url.com/api#${{ secrets.PRODUCTION_API_URL }}#g' src/environments/environment.prod.tsx
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: build
        run: |
          CI=true npm run build
